### ISSUE TITLE
[PE-D][Tester A] cannot detect possibly invalid descriptions

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-T13-1/tp#162]
![image.png](https://raw.githubusercontent.com/avielcx/ped/main/files/927b0ac1-d976-47dd-a718-ebc6d914ea75.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: avielcx/ped#19

**Comment by Bawfen** [comment]
Not sure what is the expected behaviour here, @woowenjun99 @Arif-Khalid please comment
The output from trans after doing this is shown below.
<img width="527" alt="Screenshot 2023-04-01 at 7 23 09 PM" src="https://user-images.githubusercontent.com/5654392/229285857-88752836-ad02-4b85-a846-af610a177337.png">

**Comment by Gan868611** [comment]
I think this is not an issue , `""""` is recorded as a description. We cant check the validity of a description

**Comment by Bawfen** [comment]
Not an issue since this is expected. Perhaps we can write in the user guide that there is a maximum length and a specific set of allowed characters?
